#!/usr/bin/env bash
# Applies migrations/ to the local D1 simulator. Needs no Cloudflare account.
set -euo pipefail
cd "$(dirname "$0")/.."

DB_NAME="edge-graph-rag"
# Local D1 keys its state directory by database id, so any well-formed id will
# do — but switching to a real one later starts a fresh local database.
LOCAL_DB_ID="00000000-0000-0000-0000-000000000000"

if [[ ! -f wrangler.jsonc ]]; then
	echo "==> no wrangler.jsonc — generating a local-only one from the template"
	{
		echo "// GENERATED by scripts/migrate-local.sh — not committed, LOCAL USE ONLY."
		echo "// The D1 id below is a placeholder. Run scripts/setup-cloudflare.sh for a real one."
		sed "s|__D1_DATABASE_ID__|${LOCAL_DB_ID}|" wrangler.template.jsonc
	} >wrangler.jsonc
fi

npx wrangler d1 migrations apply "${DB_NAME}" --local
