#!/usr/bin/env bash
# Creates the two Cloudflare resources this project needs and writes wrangler.jsonc.
# Safe to re-run: it skips whatever already exists.
set -euo pipefail
cd "$(dirname "$0")/.."

DB_NAME="edge-graph-rag"
INDEX_NAME="edge-graph-rag-chunks"
# @cf/baai/bge-base-en-v1.5 emits 768 dimensions; cosine is the metric the rest
# of the pipeline assumes. Both are fixed at creation time and cannot be changed.
DIMENSIONS=768
METRIC="cosine"

. scripts/_auth.sh
require_cloudflare_auth

# The database is looked up in `d1 list`, not `d1 info`: on a fresh account
# `d1 info <name>` answered 7404 "could not be found" for a database that
# `d1 list` showed and `d1 create` had just made.
d1_id() {
	npx wrangler d1 list --json | DB_NAME="${DB_NAME}" node -e '
		let raw = "";
		process.stdin.on("data", (d) => (raw += d));
		process.stdin.on("end", () => {
			const start = raw.indexOf("[");
			if (start === -1) { console.error("wrangler d1 list returned no JSON"); process.exit(1); }
			const db = JSON.parse(raw.slice(start)).find((d) => d.name === process.env.DB_NAME);
			process.stdout.write(db ? String(db.uuid ?? db.database_id ?? db.id) : "");
		});
	'
}

echo "==> D1 database: ${DB_NAME}"
# The id is account-specific, which is exactly why wrangler.jsonc is generated
# rather than committed.
DB_ID="$(d1_id)"
if [[ -n "${DB_ID}" ]]; then
	echo "    already exists, leaving it alone"
else
	npx wrangler d1 create "${DB_NAME}"
	DB_ID="$(d1_id)"
fi
if [[ -z "${DB_ID}" ]]; then
	echo "Could not find ${DB_NAME} in wrangler d1 list." >&2
	exit 1
fi

echo "==> Vectorize index: ${INDEX_NAME} (${DIMENSIONS} dims, ${METRIC})"
if npx wrangler vectorize get "${INDEX_NAME}" >/dev/null 2>&1; then
	echo "    already exists, leaving it alone"
else
	npx wrangler vectorize create "${INDEX_NAME}" \
		--dimensions="${DIMENSIONS}" \
		--metric="${METRIC}" \
		--description="Chunk embeddings for edge-graph-rag"
fi

echo "==> writing wrangler.jsonc"
{
	echo "// GENERATED by scripts/setup-cloudflare.sh — not committed."
	echo "// Edit wrangler.template.jsonc and re-run that script instead."
	sed "s|__D1_DATABASE_ID__|${DB_ID}|" wrangler.template.jsonc
} >wrangler.jsonc

echo
echo "Done. Next: ./scripts/migrate-remote.sh"
