#!/usr/bin/env bash
# Creates the two Cloudflare resources this project needs and writes wrangler.jsonc.
# Safe to re-run: it skips whatever already exists.
set -euo pipefail
cd "$(dirname "$0")/.."

DB_NAME="edge-graph-rag"
INDEX_NAME="edge-graph-rag-chunks"
# @cf/baai/bge-base-en-v1.5 emits 768 dimensions; cosine is the metric the rest
# of the pipeline assumes. Both are fixed at creation time and cannot be changed.
DIMENSIONS=768
METRIC="cosine"

. scripts/_auth.sh
require_cloudflare_auth

echo "==> D1 database: ${DB_NAME}"
if npx wrangler d1 info "${DB_NAME}" --json >/dev/null 2>&1; then
	echo "    already exists, leaving it alone"
else
	npx wrangler d1 create "${DB_NAME}"
fi

# The id is account-specific, which is exactly why wrangler.jsonc is generated
# rather than committed.
DB_ID="$(
	npx wrangler d1 info "${DB_NAME}" --json | node -e '
		let raw = "";
		process.stdin.on("data", (d) => (raw += d));
		process.stdin.on("end", () => {
			const start = raw.indexOf("{");
			if (start === -1) { console.error("wrangler d1 info returned no JSON"); process.exit(1); }
			const info = JSON.parse(raw.slice(start));
			const id = info.uuid ?? info.database_id ?? info.id;
			if (!id) { console.error("no database id in: " + Object.keys(info).join(", ")); process.exit(1); }
			process.stdout.write(String(id));
		});
	'
)"

echo "==> Vectorize index: ${INDEX_NAME} (${DIMENSIONS} dims, ${METRIC})"
if npx wrangler vectorize get "${INDEX_NAME}" >/dev/null 2>&1; then
	echo "    already exists, leaving it alone"
else
	npx wrangler vectorize create "${INDEX_NAME}" \
		--dimensions="${DIMENSIONS}" \
		--metric="${METRIC}" \
		--description="Chunk embeddings for edge-graph-rag"
fi

echo "==> writing wrangler.jsonc"
{
	echo "// GENERATED by scripts/setup-cloudflare.sh — not committed."
	echo "// Edit wrangler.template.jsonc and re-run that script instead."
	sed "s|__D1_DATABASE_ID__|${DB_ID}|" wrangler.template.jsonc
} >wrangler.jsonc

echo
echo "Done. Next: ./scripts/migrate-remote.sh"
